### ISSUE TITLE
Попеременно глючат сенсоры, если их несколько на одну остановку

### ISSUE THREAD

**Issue by kirik911** [egmen/moscow_transport#4]
Есть одна остановка с двумя маршрутами от нее: до вокзала и до метро.
Соответственно, создал два датчика, привязанных к одной остановке. Отличия только в том, что в одной выбрал маршрут 714, а в другой 414.
Для теста добавил ещё сенсор с этой остановкой, но с обоими марштурами.
Каждый раз при перезагрузке сервера происходит один из вариантов:
- загружается только один из сенсоров из набора общей остановки, остальные - отсутствуют.
- не загружается ни один из сенсоров из набора общей остановки
- появляются ранее созданные, но удалённые позже сенсоры, дублирующие существующие.

(если создать один сенсор в рамках одной остановки, все работает)

```
# первый сенсор работает всегда нормально, даже если его поставить в конец списка
  - platform: moscow_transport
    name: 714 - от метро
    stop_id: 04bcb88b-6829-4caa-b72d-696a7bed98e7
    routes:
      - 714
 # эти следующие попеременно могут не загрузиться при новой перезагрузке
  - platform: moscow_transport
    name: 414 и 714
    stop_id: 636548cd-af01-47c5-90c6-0d4514ec0ff8
    routes:
      - 414
      - 714
  - platform: moscow_transport
    name: До метро - 414
    stop_id: 636548cd-af01-47c5-90c6-0d4514ec0ff8
    routes:
      - 414
  - platform: moscow_transport
    name: До вокзала - 714
    stop_id: 636548cd-af01-47c5-90c6-0d4514ec0ff8
    routes:
      - 714
```
